### PR TITLE
chore: increase db-service version for pg,hana,sqlite

### PR DESCRIPTION
**Pull request by johannes-vogel**
@patricebender Do you think that works if we merge this PR just before the release?

### CODE REVIEW

**Comment by patricebender** [comment]
this should work in the release PR. There the db-service@1.7.0 is already available.

**Comment by johannes-vogel** [comment]
> this should work in the release PR. There the db-service@1.7.0 is already available.

👍  thought so as well.

**Review by patricebender — APPROVED** [review]

**Review by BobdenOs — APPROVED** [review]

**Comment by patricebender** [comment]
Next time we should use semantic commit type `deps` here, but as this was merged to the release branch, I had to manually add this to the changelog regardless.

**Comment by johannes-vogel** [comment]
> Next time we should use semantic commit type `deps` here, but as this was merged to the release branch, I had to manually add this to the changelog regardless.

the problem is that you can only force merge it to main, as the versions do not yet exist.

**Pull request merged**
