### PR TITLE
cqn4sql: make sure to always use calculated alias in custom on conditions

### PR DESCRIPTION
**Pull request by patricebender**
Inspired by #169

---

the issue here was that we had a where condition like

`where exists foo[id=1] or exists foo[id=2]` with foo being an association `foo : Association to one Foo on foo.ID = foo_ID;`.

While building up the where exists subqueries, we calculate unique table aliases for `foo`, which results in a table alias `foo2` for the second condition of the initial where clause. Now, if we incorporate the on-condition into the where clause of the second where exists subquery, we must replace the table alias `foo` from the on-condition with `foo2`.

### CODE REVIEW

**Comment by stewsk** [comment]
The test case provided here is (if I'm not mistaken) the same as in https://github.com/cap-js/cds-dbs/pull/169. But that test didn't discover the problem described in https://github.com/cap-js/cds-dbs/pull/173#issue-1852975234 - or did it?

**Comment by patricebender** [comment]
> Reference in new issue

nope it didn't, im still working on that.

**Comment by sjvans** [comment]
> > Reference in new issue
> 
> nope it didn't, im still working on that.

for this pr?

**Comment by patricebender** [comment]
> > > Reference in new issue
> 
> > 
> 
> > nope it didn't, im still working on that.
> 
> 
> 
> for this pr?

Yes, I will add it as part of this pr hopefully today

**Comment by patricebender** [comment]
@stewsk @sjvans please have a look at #173 which showcases the error which was reported in the cap issue.

**Comment by stewsk** [comment]
Is it possible to have a dedicated cqn4sql test for the situation described in https://github.com/cap-js/cds-dbs/pull/174 ?

**Comment by patricebender** [comment]
> Is it possible to have a dedicated cqn4sql test for the situation described in #174 ?

yes you are right, this way it is much clearer what the issue is. I replaced the end-2-end test with a proper cqn4sql test illustrating the issue. :)

**Pull request merged**
