### PR TITLE
fix(aliasing): alias name must be kept as requested

### PR DESCRIPTION
**Pull request by johannes-vogel**
Trying to reproduce https://github.com/cap-js/cds-dbs/issues/229

@BobdenOs Do you know by any chance whether this can be depending on pg version?

### CODE REVIEW

**Comment by BobdenOs** [comment]
@johannes-vogel from the original issue it looks like it is being selected from the native table. Which means that it is not going through the same process as tables which are part of the model. Especially as the original issue uses `"` in the alias which looks like it is trying to prevent SQL syntax errors. Which would no longer be needed with the new database service as it would quote when needed.

**Comment by johannes-vogel** [comment]
> @johannes-vogel from the original issue it looks like it is being selected from the native table. Which means that it is not going through the same process as tables which are part of the model. Especially as the original issue uses `"` in the alias which looks like it is trying to prevent SQL syntax errors. Which would no longer be needed with the new database service as it would quote when needed.

Thanks, now I can reproduce it.

**Comment by BobdenOs** [comment]
This is a side effect of our minimal quoting approach. Where Postgres assumes every column to be lower case. Like how HANA assumes every column to be upper case.

**Comment by johannes-vogel** [comment]
> This is a side effect of our minimal quoting approach. Where Postgres assumes every column to be lower case. Like how HANA assumes every column to be upper case.

I don't think that's what someone would expect. If I provide an alias within CQN, I'd expect that the result contains the property as specified in the CQN (regardless whether we know the entity or not).

**Comment by johannes-vogel** [comment]
@BobdenOs I think we should allow selects the same way as we do for insert/update. I've updated the test to be executable on any db, but cqn2sql doesn't work with unknown entities yet. Could you please have a quick look on that?

**Comment by patricebender** [comment]
I believe this can be closed, at least the alias is now kept as requested.

**Pull request closed without merging**
